#!/usr/bin/env bun
// Generate a reviewable systemd drop-in. This script never installs it or restarts a service.
import { resolve4, resolve6 } from "node:dns/promises";
import { readFile, writeFile } from "node:fs/promises";
import { isIP } from "node:net";
import { isPublicAddress, validateCallbackHosts } from "../mcp/src/webhook.ts";

export type AddressResolver = (host: string) => Promise<readonly string[]>;

export const resolveAddresses: AddressResolver = async (host) => {
  const results = await Promise.allSettled([resolve4(host), resolve6(host)]);
  const addresses: string[] = [];
  for (const result of results) {
    if (result.status === "fulfilled") addresses.push(...result.value);
    else if (result.reason?.code !== "ENODATA") throw new Error(`DNS resolution failed for ${host}`);
  }
  return addresses;
};

export async function readCallbackHosts(configPath: string): Promise<string[]> {
  const text = await readFile(configPath, "utf8");
  let config: unknown;
  try { config = JSON.parse(text); } catch { throw new Error("MCP config is not valid JSON"); }
  const hosts = (config as { events?: { callbackHosts?: unknown } } | null)?.events?.callbackHosts;
  if (!Array.isArray(hosts) || !hosts.every((host) => typeof host === "string") || !hosts.length) {
    throw new Error("MCP config must contain a nonempty events.callbackHosts array of exact hostnames");
  }
  return validateCallbackHosts(hosts);
}

export async function generateEgressPolicy(
  callbackHosts: readonly string[],
  resolver: AddressResolver = resolveAddresses,
  generatedAt: Date = new Date(),
): Promise<{ hosts: string[]; addresses: string[]; dropIn: string }> {
  if (!callbackHosts.length) throw new Error("At least one exact callback hostname is required");
  const hosts = [...new Set(validateCallbackHosts(callbackHosts))].sort();
  if (hosts.some((host) => isIP(host))) throw new Error("Callback policy requires DNS hostnames, not IP literals");
  const records = await Promise.all(hosts.map(async (host) => ({ host, addresses: await resolver(host) })));
  const addresses = new Set<string>();
  for (const record of records) {
    if (!record.addresses.length) throw new Error(`No destination addresses for ${record.host}`);
    for (const address of record.addresses) {
      if (!isIP(address) || !isPublicAddress(address)) throw new Error(`Non-public destination address for ${record.host}`);
      addresses.add(address.toLowerCase());
    }
  }
  const sorted = [...addresses].sort();
  const allow = sorted.map((address) => `${address}/${isIP(address) === 4 ? 32 : 128}`);
  const dropIn = [
    "# Generated by scripts/events-egress-policy.ts. Review before installing.",
    `# DNS snapshot: ${generatedAt.toISOString()}`,
    `# Exact callback hosts: ${hosts.join(", ")}`,
    "# DNS changes require regeneration. No service changes are performed by the generator.",
    "# IPAddressAllow cannot distinguish hosts or ports sharing an address.",
    "# The webhook transport separately enforces exact hostnames, HTTPS port 443 and TLS.",
    "[Service]",
    "IPAddressDeny=any",
    "# Reset old callback addresses while retaining the bridge's loopback and tailnet access.",
    "IPAddressAllow=",
    "IPAddressAllow=localhost 100.64.0.0/10 fd7a:115c:a1e0::/48",
    ...allow.map((address) => `IPAddressAllow=${address}`),
    "",
  ].join("\n");
  return { hosts, addresses: sorted, dropIn };
}

async function main() {
  const args = Bun.argv.slice(2);
  let configPath: string | undefined;
  let outputPath: string | undefined;
  for (let i = 0; i < args.length; i++) {
    const flag = args[i];
    if (flag !== "--config" && flag !== "--output") throw new Error("Usage: bun scripts/events-egress-policy.ts --config MCP_CONFIG [--output NEW_FILE]");
    const value = args[++i];
    if (!value || value.startsWith("--")) throw new Error(`Missing value for ${flag}`);
    if (flag === "--config") {
      if (configPath) throw new Error("--config may be supplied only once");
      configPath = value;
    } else {
      if (outputPath) throw new Error("--output may be supplied only once");
      outputPath = value;
    }
  }
  if (!configPath) throw new Error("Usage: bun scripts/events-egress-policy.ts --config MCP_CONFIG [--output NEW_FILE]");
  const { dropIn } = await generateEgressPolicy(await readCallbackHosts(configPath));
  if (outputPath) await writeFile(outputPath, dropIn, { flag: "wx", mode: 0o644 });
  else process.stdout.write(dropIn);
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : "Could not generate callback egress policy");
    process.exitCode = 1;
  });
}
